workflows:
  android_build:
    name: Build Android App (Java)
    max_build_duration: 60
    environment:
      flutter:{}
    scripts:
      - name: Grant execute permission for gradlew
        script: chmod +x ./gradlew
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
